sudo: required
dist: trusty # (14.04)
# xenial (16.04) is not supported yet

language: cpp
compiler:
  - clang

git:
  depth: 1

before_install:
  - sudo apt-get -y install build-essential libtool make cmake cmake-data openssl libgoogle-perftools-dev
  - sudo apt-get -y install libssl-dev libmysqlclient-dev libmysql++-dev libreadline6-dev zlib1g-dev libbz2-dev libace-dev
  - git config user.email "travis@build.bot" && git config user.name "Travis CI"
  - git tag -a -m "Travis build" init

install:
  - mkdir build
  - cd build
  - cmake ../ -DCMAKE_INSTALL_PREFIX=check_install -DTOOLS=0 -DSCRIPTS=1
  - cd ..

script:
  - $CXX --version
  - cd build
  - make -j 8 -k && make install
  - cd check_install/bin

